### PR TITLE
chore(VLE TopBar): Convert to Angular

### LINKED ISSUE #471: Upgrade VLE topbar to Angular
Also make necessary modules.

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Converted TopBar into Angular component and made TopBarModule
- Put StudentAccountMenu and NotificationsMenu into modules and moved into part of TopBarModule

## Test
- Student VLE looks and works as before
   - notifications count update
   - can open/close notifications dialog
   - can open/close student account dialog
   - progress bar (circle) updates as you complete project
   - click on logo takes you to student home page
- Preview looks and works as before
   - turn constraint off 
   - progress bar (circle) updates as you complete project
   - click on logo takes you to 
      - main homepage (if not logged in)
      - teacher homepage (if logged in as teacher)

Closes #471

### CODE REVIEW

**Comment by hirokiterashima** [comment]
@breity I've really messed up the styling, as you can see here. :P Please style/clean the files as you see fit.
Screen Shot 2022-01-27 at 5 51 20 PM

**Review by breity — APPROVED** [review]
I fixed and cleaned up the styling and layout in the TopBar. I made the student account menu buttons keyboard accessible. I also converted the notifications menu to a dialog, as I was previously using a MatList inside the notifications MatMenu, which was not keyboard accessible.

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
1. In Preview mode, the "Turn Off Constraints" button used to be raised but now it's flat. Should it be raised?

2. When not signed in and Previewing a unit, opening the account menu and clicking "Go Home" just refreshes the VLE.

3. There are some conflicts when merging into develop.

**Comment by breity** [comment]
@geoffreykwan Thanks. I addressed 1 and 3. I made the "Turn Off Constraints" button a mat-flat-button, which changes the color to make it recognizable as a button. I also resolved the conflicts.

Hiroki will make a separate issue for 2.

**Comment by geoffreykwan** [comment]
Does the "Turn Off Constraints" button stand out too much now?
Screen Shot 2022-02-09 at 12 33 44 PM

Would it be better if it looked more like it did before like this below? To make it look like this I changed it to mat-raised-button and set background-color: #1c8ca8 on the button.
Screen Shot 2022-02-09 at 12 33 15 PM

**Comment by breity** [comment]
@geoffreykwan As discussed, I changed the remove constraints button style to stroked.
image

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
