### PR TITLE
ManageStudentsRewrite: implemented change period dialog

### LINKED ISSUE #246: Manage Students: change team period
### Description

In the Manage Student re-write v1:
- change period link opens a dialog to choose new period for the team

image

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Implemented change period dialog from the new ManageStudents page
- Added observable to ConfigService for alerting when config has been retrieved
- Broke up i18n in ManagePeriod template heading

## Test
- First test API changes: https://github.com/WISE-Community/WISE-API/pull/19. This code will make a request to the new api endpoint
- Clicking on "change period" link in the ManageWorkgroup component should open a Change Period dialog
- Period select dropdown should show only the periods that the workgroup can move to. It should hide All Periods and current period options.
- Changing the period should close the dialog and move the workgroup to the new period
- You can cancel out of changing the workgroup's period.

## Notes
- The period drop down in the upper-right corner of the CM does not update the team count properly. This is an existing bug and will be fixed separately.

Closes #246

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Changing a student's period works well. I noticed some things as a shared teacher though.

- If "View Student Names" is unchecked for a shared teacher, we should show something in place of where the names would usually go like "Student #".

- If "Grade and Manage" is unchecked for a shared teacher, the "Change Period" link should not show up since they aren't allowed to change a student's period.

Screenshot 2021-07-14 134540

Screenshot 2021-07-14 115437

**Comment by hirokiterashima** [comment]
@geoffreykwan good catch. We fixed the issue and added unit tests. Can you re-review?

**Comment by hirokiterashima** [comment]
@geoffreykwan I fixed the issue where shared teacher without canViewStudentNames permission could not see the change period dialog.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
