### PR TITLE
refactor(ChooseNewComponent): Convert to standalone

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Convert ChooseNewComponent to standalone component
- Clean up code
   
## Test
- In the add new component dialog in the AT
   - the component options appear and work as before
   - "cancel" button works as before
   - "import" button works as before

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
The add component view works but the create new step view no longer shows the component type buttons.

**Comment by hirokiterashima** [comment]
Good catch. Fixed. PTAL.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
