### PR TITLE
feat(Entire Application): Upgrade to Angular 16

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Upgrade Angular from 15 to 16 and related dependencies

## Test
- Everything works and looks the same as before for VLE, Preview, CM, AT, and site

### CODE REVIEW

**Comment by hirokiterashima** [comment]
There are few styling issues that I found so far. @breity can you please take a look?

In Student VLE -> Feedback from teacher box, the arrow is jutting out too much to the left of the box:
Screenshot 2023-10-18 at 6 26 14 PM

In Unit plan view and grade-by-step view, the progress bar has a scroll bar: 
Screenshot 2023-10-18 at 6 26 00 PM

**Review by breity — APPROVED** [review]
Looks good.

I fixed the mentioned styling issues plus some others that I found.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Comment by hirokiterashima** [comment]
Updated to use https://www.npmjs.com/package/@wise-community/angular-password-strength-meter, which works with Angular 16. Also merged in latest from the develop branch. PTAL.

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
The font in the open response student textarea has changed.

Screenshot 2023-11-01 121635

**Comment by hirokiterashima** [comment]
Good catch. This looks like an effect of the changes in the Angular 16 material design library. @breity and I fixed it by adding font styles to the textarea element. Let's look into converting this to using Angular input in a future task. PTAL.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by breity — APPROVED** [review]

**Pull request merged**
