### PR TITLE
feat(Authoring): Add copy button to all steps

### LINKED ISSUE #1645: feat(Authoring): In project view, add copy button to steps

### PR DESCRIPTION
**Pull request by geoffreykwan**
## Changes
- Added copy button to all steps

## Test
- Make sure the copy button on the steps works

Closes #1645

### CODE REVIEW

**Review by hirokiterashima — CHANGES_REQUESTED** [review]
Can you split this PR into smaller PR's- one for move and one for copy? It'll make things easier for me to review.

**Comment by geoffreykwan** [comment]
This is too big? It's about 60 lines of changes and the guideline says 100 lines is a small change. There are no complex changes either.

**Comment by hirokiterashima** [comment]
Yah, the change set is not that large, but this PR contains two different features. I want to review one feature at a time in order to give the best feedback.

**Comment by geoffreykwan** [comment]
I've removed the move button.

**Review by hirokiterashima — APPROVED** [review]
LGTM.

Can you change ```copy(event: any)``` to ```copy(event: Event)``` before merge?

Also, I noticed inconsistencies in capitalizing the tooltips, e.g. "Copy step" vs "Copy Component". Let's discuss this and address it in a separate task.

**Pull request merged**
