### PR TITLE
chore(Preview Component): Convert to Angular

### LINKED ISSUE #546: Convert PreviewComponent to Angular
Convert from AngularJS to Angular

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Create PreviewComponentButton to launch Angular Material Dialog that renders PreviewComponent
- Rename mode 'authoringComponentPreview' to 'preview'

## Test
- In the AT, component preview works by clicking on Preview Component buttons at the top and bottom of each component
- In the CM, component preview shows up in the "Step Info" dialog

## Notes
- AngularJS way of watching componentContent for changes and recompiling did not translate well to Angular way, so we had to abandon real-time preview for now in the AT.

Closes #546

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
1. The preview popup should have a close button. Maybe an x button at the top right of the popup?
2. There are a couple components (Concept Map, Draw, Label) where previously the author could use the preview to author and save starter states. They can no longer do this anymore in the new popup.

**Comment by hirokiterashima** [comment]
@geoffreykwan made requested changes. Please re-review.

@breity can you style the new save/delete starter state buttons and dialog?

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
The save/delete starter state functionality looks good.

I discovered an issue with previewing Open Response CRater components. If you preview an Open Response that has a CRater item and click Submit, it will freeze the Authoring Tool and you will need to refresh the page to get out of it. On production when you click the Submit button nothing happens. You can test it with this Item ID

```MusicalInstruments_Speed_score-ki_idea-ki_nonscorable```

Screen Shot 2022-03-22 at 10 50 27 AM

**Comment by hirokiterashima** [comment]
@geoffreykwan Good catch. I fixed the underlying issue where mode was not being used to show/hide component annotations. Please re-test CRater in component preview, whole preview, and student views.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by breity — APPROVED** [review]

**Pull request merged**
