### PR TITLE
Add step: automated assessment option and optional initial components

### LINKED ISSUE #54: Add Step Wizard: automated assessment and create your own options
### Description

In the add step wizard, add the "automated assessment" option. This should launch the existing automated assessment choose/configure/select location sequence.

In the add step wizard, add the "create your own" option. This should take the author to a page to enter a step title and then a page to select a location for the new step (existing functionality).

Screen Shot 2021-04-05 at 4 35 45 PM

### LINKED ISSUE #60: Create Your Own Step: select starting components
### Description

In the "Create Your Own" step view in the add step wizard, allow author to select multiple components to add to the new step. They can add, order, and delete component to the new step.

image
image

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Added a choose template page with the choices "Automated Assessment" and "Create Your Own" (#54)
- Moved Automated Assessment wizard from Structure Authoring wizard to the Add Step wizard (#54)
- Added option to select multiple initial components when choosing "Create Your Own" (#60)
- Adding the new node (both Create Your Own and Automated Assessment) will then open the node authoring view, instead of the project view (#54)

## Test
1. Add a new Create Your Own Node
   1. Enter/leave blank step title
   2. Select 0 or more initial components. Test ordering, deleting components from list. Test adding multiple components of the same type
2. Add an Automated Assessment Node (lets you choose an automated assessment item, customize some settings like feedback text and show score/feedback and select a location)
3. When the new node is added, it displays the node authoring view for the newly-added node, instead of the project view
4. Go back/cancel out of the wizard

## Other notes
@breity please edit UI as you see fit. I mainly referenced the UI in structured authoring and used the styles in the Angular UI Drag/Drop example: https://material.angular.io/cdk/drag-drop/overview

Closes #54
Closes #60

### CODE REVIEW

**Review by geoffreykwan — APPROVED** [review]
Looks good. The "Step Title" input is kinda small (in width). Maybe we should make it wider?

**Review by breity — APPROVED** [review]
Working great.

I updated styles and layout and also merged latest from develop and added updated messages.xlf.

I also changed the  initial component buttons to use the component type's label instead of the type itself (e.g. "Open Response" vs "OpenResponse") and changed the label for HTML components to "Rich Text (HTML)".

@geoffreykwan and @hirokiterashima, take a look and let me know if you see any issues.

**Comment by hirokiterashima** [comment]
I reviewed your UI changes @breity.

Looks great! So much cleaner and easier to use! 👏👏👏

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
