### PR TITLE
Merge old WISE component tests into the new WISE components

### LINKED ISSUE #301: Merge old WISE component tests into the new WISE components
Merge the tests in src/assets/wise5/test-unit/components into the new WISE components in src/assets/wise5/components.

### PR DESCRIPTION
**Pull request by geoffreykwan**
Run the tests and make sure they pass.

Closes #301

### CODE REVIEW

**Comment by hirokiterashima** [comment]
1. edit-table-advanced.component.spec.ts is not running any tests. Should remove or enable tests?

2. In graph-student.component.ts, wouldn't it be simpler to rewrite
```
FROM:
import * as covariance from 'compute-covariance';
TO:
import * as calculateCovariance from 'compute-covariance';
```
and remove the new calculateCovariance() function?  I haven't tested this out yet, but wondered if a new function definition can be avoided here.

**Comment by geoffreykwan** [comment]
I moved the tests from tableAuthoringController.spec.js to edit-table-advanced.component.spec.ts for now since tableAuthoringController.spec.js no longer exists and EditTableAdvancedController has not been converted to new Angular yet. Once we convert EditTableAdvancedController to new Angular, we can enable the tests.

**Comment by hirokiterashima** [comment]
ok sounds good.

**Review by hirokiterashima — APPROVED** [review]
LGTM

**Pull request merged**
