### PR TITLE
Show latest posts from Discourse news category on site home

### LINKED ISSUE #220: Show latest news from WISE Community on site hompage
Show the 3 most recent posts from https://wise-discuss.berkeley.edu/c/news-announcements/7 on site homepage.

Also:
- Change "News" menu and footer links to "Community" and point to https://wise-discuss.berkeley.edu.
- Change "News" call-to-action section at bottom of homepage to "Community" and link to https://wise-discuss.berkeley.edu.

### PR DESCRIPTION
**Pull request by breity**
## Changes
Added a latest news component that displays links to the 3 latest topics in a specified Discourse category. Latest news is displayed inside the HeroSection on the site home. HeroSection was modified to display optional side content.

Also replaced all "news" links on the site home, menus, and footer with links to the WISE Community (Discourse).

Closes #220. 

## Test
- Load the site home and make sure the last 3 posts from https://wise-discuss.berkeley.edu/c/news-announcements/7 are shown and that clicking on each takes you to the post.
- Test on different screen sizes to make sure layout looks good and all the Hero content is readable.
- Also ensure that the "More news" link takes you to the Discourse category.
- Check that all the "Community" links work in the menus, footer, and Community call-to-action section at the bottom of the site home.

### CODE REVIEW

**Comment by geoffreykwan** [comment]
Should each news thread title have a bullet to make it easier to see that they are different titles instead of a single block of text? This is what it could look like.

Screenshot 2021-06-23 155924

When the screen width gets smaller, should each news thread title be on their own line? This is what it looks like now.

Screenshot 2021-06-23 164349

**Comment by breity** [comment]
@geoffreykwan Thanks. Good suggestion for adding bullets. I think it looks clearer with them too, so I added them. For smaller screens, I was keeping the news inline because otherwise the news block can get too tall and some hero content gets cut off.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by hirokiterashima — APPROVED** [review]
LGTM

**Pull request merged**
