### PR TITLE
chore(Classroom Monitor): Upgrade component to Angular 

### LINKED ISSUE #978: Convert ClassroomMonitorController to Angular Component
Keep using AngularJS views (using UpgradeModule) for now. We will replace them with Angular routes later.

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Notes
- @breity please style as you see fit. There are some issues:

   - The MainMenuComponent (the drawer that displays options like export when you click on the 3 lines on top-left) does not appear anymore. It looks like it's hidden behind the other layouts
Screenshot 2023-01-26 at 12 47 58 PM

   - The TopBarComponent (the top div containing run name, notification button, account button, etc) disappears when scrolling down, when it should always remain visible
Screenshot 2023-01-26 at 12 46 44 PM

   - In the SideMenu, choosing anything other than "Grade by Step" hides the SideMenu and moves the Teacher Notebook to the top of the page  
Screenshot 2023-01-26 at 12 45 18 PM

## Changes
- Upgrade ClassroomMonitorController to Angular component
- Note: we still use the AngularJS state params for now. This will be replaced with Angular routes in a future task

## Test
- Routes work (Milestone, Grade by step/team, Manage students, notebook, export), and the view title like "Grade by Step", "Grade by Team" appears correctly
- Select period dropdown appears on appropriate routes
- Misc.
   - Session timeout warning displays, and can extend session or log out
   - Server connection lost snack bar message displays

Closes #978

### CODE REVIEW

**Review by breity — APPROVED** [review]
LGTM.

I updated layout and styling. Take a look to make sure it all looks good. If so, should be ready to merge.

**Comment by hirokiterashima** [comment]
Thanks @breity. It looks good. @geoffreykwan, can you take a quick final look?

I found that the "Showing X/X" component filter dropdown at the top right doesn't update from step to step. This is an issue on production too, so I will write it up in a separate issue.
Screenshot 2023-01-31 at 10 29 50 AM

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Clicking previous or next in the workgroup select doesn't navigate to other workgroups.
1. Go to the Grade By Team view
2. Click on a workgroup
3. Try to change the workgroup by clicking the previous or next arrow buttons or using the select drop down
4. The workgroup will not change even though it should

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
