### PR TITLE
refactor(Component): Pass in Component to Preview and Student VLE

### LINKED ISSUE #904: Refactor: Pass in Component to PreviewComponentComponent and ComponentStudent
### Description

Right now we pass in nodeId and componentContent to PreviewComponentComponent and ComponentStudent, and making those components look up the Component. Instead, we should look up the Component and pass it into those components. This will simplify inputs to the PreviewComponentComponent/ComponentStudent and clarify that those components require a Component.

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Pass Component as input to PreviewComponentComponent and ComponentStudent instead of nodeId/componentContent. This simplifies the PreviewComponentComponent/ComponentStudent classes and clarifies that those components require a Component (which they both do in order to function)
- Update tests
- Remove unused code

## Test
- VLE, Preview, AT, and CM work as before

Closes #904

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
If you open the "Step Info" popup in the Grade By Step view, there's a console error and the components are not rendered.
1. Open the Classroom Monitor
2. Click on a step
3. Click "Step Info" button in the upper right

```
TypeError: Cannot read properties of undefined (reading 'content')
    at PreviewComponentComponent_Template (preview-component.component.html:1:6)
    at executeTemplate (core.mjs:9632:9)
```

Remove unused imports in these files
- animation-student.component.spec.ts
- open-response-student.component.spec.ts
- table-student.component.spec.ts

**Comment by hirokiterashima** [comment]
@geoffreykwan Thanks. I fixed the issue and removed the unused imports and function.

The template node-info.component.html looks a bit odd now, where it's getting ```component.component```. Ideally component is the Component object, but that would require a lot of changes. I suppose we can refactor this in a future task.
```
<preview-component [component]="component.component" [periodId]="periodId">
```

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by breity — APPROVED** [review]
Functionality looks good.

Perhaps we should rename [getComponent](https://github.com/WISE-Community/WISE-Client/blob/078f3c31087a6942927296338a8f79a734e5cf8d/src/assets/wise5/services/projectService.ts#L1201) and [getComponents](https://github.com/WISE-Community/WISE-Client/blob/078f3c31087a6942927296338a8f79a734e5cf8d/src/assets/wise5/services/projectService.ts#L1218) in `projectService.ts` since they return ComponentContent (not WISEComponent) objects. This could be done in another issue.

**Comment by hirokiterashima** [comment]
@breity yupp, let's rename in a separate PR. Thanks.

**Pull request merged**
