### PR TITLE
feat(FeedbackRule): isLowestWorkgroupIdInPeerGroup token

### LINKED ISSUE #1418: Feedback Rule new "isLowestWorkgroupIdInPeerGroup" token
Add support for ```isLowestWorkgroupIdInPeerGroup``` token that returns true when the student's workgroup id is lower than all the other student's workgroup id's. This token should only be used in Dynamic Prompt and Question Bank activities, and the activities must specify a Peer Grouping. 

Examples (my workgroup id = 2)
1. Returns false if PeerGroup member's ids are: 
   - [1,2]
   - [1,2,3]
3. Returns true if PeerGroup member's ids are: 
   - [2]
   - [2,3]
   - [2,3,4]

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
Add support for ```isLowestWorkgroupIdInPeerGroup``` token that returns true when the student's workgroup id is lower than all the other student's workgroup id's in the same PeerGroup. This token should only be used in Dynamic Prompt and Question Bank activities, and the activities must specify a Peer Grouping. 

Examples (my workgroup id = 2)
1. Returns false if PeerGroup member's ids are: 
   - [1,2]
   - [1,2,3]
2. Returns true if PeerGroup member's ids are: 
   - [2]
   - [2,3]
   - [2,3,4]

## Test
- Add ```isLowestWorkgroupIdInPeerGroup``` in the FeedbackRule expression for Dynamic Prompt, Question Bank with (remember to specify PeerGrouping) and make sure that the rule is matched if the student's workgroup ID is the lowest in the PeerGroup. If should not match otherwise. 
- ```!isLowestWorkgroupIdInPeerGroup``` should match if your workgroup ID is *not* the lowest in the PeerGroup.
- Existing Peer Chat steps with Dynamic Prompt, Question Bank work as before

Closes  #1418

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
When I use isLowestWorkgroupIdInPeerGroup() by itself in an expression it works properly.

I get an error when I use isLowestWorkgroupIdInPeerGroup() with &&. Here is how to reproduce the error.

1. Create a Multiple Choice component that has the choices A, B, C.

2. Author Peer Chat that references the Multiple Choice component and Dynamic Prompt rules using && like these below

Prompt Rule 1
Expression: isLowestWorkgroupIdInPeerGroup() && myChoiceChosen("your-choice-id-for-a")
Prompt: You are the lowest workgroup id and chose A.

Prompt Rule 2
Expression: isLowestWorkgroupIdInPeerGroup() && myChoiceChosen("your-choice-id-for-b")
Prompt: You are the lowest workgroup id and chose B.

Prompt Rule 3
Expression: isLowestWorkgroupIdInPeerGroup() && myChoiceChosen("your-choice-id-for-c")
Prompt: You are the lowest workgroup id and chose C.

3. Preview the project
4. Go to the Multiple Choice step and submit B or C (if you choose A, the problem will not occur)
5. Go to the Peer Chat step and you will not see any Dynamic Prompt and you will see this error in the console

```
ERROR TypeError: response.getDetectedIdeaNames is not a function
    at IdeaTermEvaluator.evaluate (IdeaTermEvaluator.ts:18:45)
    at FeedbackRuleEvaluatorMultipleStudents.ts:56:24
    at Array.some (<anonymous>)
    at FeedbackRuleEvaluatorMultipleStudents.evaluateTerm (FeedbackRuleEvaluatorMultipleStudents.ts:55:22)
    at FeedbackRuleEvaluatorMultipleStudents.satisfiesSpecificRule (FeedbackRuleEvaluator.ts:95:19)
    at FeedbackRuleEvaluatorMultipleStudents.satisfiesRule (FeedbackRuleEvaluator.ts:39:14)
    at FeedbackRuleEvaluator.ts:31:30
    at Array.find (<anonymous>)
    at FeedbackRuleEvaluatorMultipleStudents.getFeedbackRule (FeedbackRuleEvaluator.ts:31:10)
```

If I use the same expressions for a Question Bank, the Question Bank works properly and does not throw an error.

I think it may have to do with Question Bank using CRaterResponse here
https://github.com/WISE-Community/WISE-Client/blob/f9d216985c3ae02e434936a2cca0a69e40961801/src/assets/wise5/components/peerChat/peer-chat-question-bank/peer-chat-question-bank.component.ts#L82

and Dynamic Prompt using Response here
https://github.com/WISE-Community/WISE-Client/blob/f9d216985c3ae02e434936a2cca0a69e40961801/src/assets/wise5/directives/dynamic-prompt/DynamicPromptMultipleChoiceEvaluator.ts#L10

A Response object does not have the getDetectedIdeaNames() function which is what is throwing the error when IdeaTermEvaluator.evaluate() gets called.

When TermEvaluatorFactory.getTermEvaluator() is passed "false", it returns the IdeaTermEvaluator but maybe we should create a BooleanTermEvaluator and return that instead of having IdeaTermEvaluator handle booleans.

https://github.com/WISE-Community/WISE-Client/blob/f9d216985c3ae02e434936a2cca0a69e40961801/src/assets/wise5/components/common/feedbackRule/TermEvaluator/TermEvaluatorFactory.ts#L33

**Comment by hirokiterashima** [comment]
@geoffreykwan good catch and suggestion. I created BooleanTermEvaluator and moved the testing of "true" and "false" string tokens there. This seems to fix the issue you found. PTAL.

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Functionality works well.

This should be multiple tests.

https://github.com/WISE-Community/WISE-Client/blob/c79835eb397f3313590c5879135b37d2ac5f365a/src/assets/wise5/components/common/feedbackRule/TermEvaluator/IdeaTermEvaluator.spec.ts#L5-L16

This should be multiple tests and include the new tokens like isLowestWorkgroupIdInPeerGroupTerm and isBooleanTerm.

https://github.com/WISE-Community/WISE-Client/blob/c79835eb397f3313590c5879135b37d2ac5f365a/src/assets/wise5/components/common/feedbackRule/TermEvaluator/TermEvaluatorFactory.spec.ts#L8-L29

**Review by breity — CHANGES_REQUESTED** [review]
Functionality works well.

I agree that we should add test cases for the new tokens to `TermEvaluatorFactory.spec.ts`.

Looks like `accumulatedIdeaCountMoreThan`, `accumulatedIdeaCountLessThan`, `accumulatedIdeaCountEquals` are also missing (not related to this PR).

**Comment by hirokiterashima** [comment]
@geoffreykwan and @breity I addressed those requested changes. PTAL.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by breity — APPROVED** [review]
Looks good. 👍

**Pull request merged**
