### PR TITLE
feat(Authoring): Collapse components

### LINKED ISSUE #1199: feat(Authoring): Collapse components
When step authoring view is loaded, have all the components collapsed. The author can then click on a component to expand it. Also provide "Expand All" and "Collapse All" buttons.

### PR DESCRIPTION
**Pull request by geoffreykwan**
## Changes

- When a step is opened in the Authoring Tool, all the components are collapsed
- You can click on a component bar to expand and collapse it
- There are "Expand All Components" and "Collapse All Components" buttons
- When a new component is added to a step, the component is immediately expanded
- When a new step is created, all the components in the step are immediately expanded

## Test

Make sure all of these things work
- When a step is opened in the Authoring Tool, all the components are collapsed
- You can click on a component bar to expand and collapse it
- The "Expand All Components" and "Collapse All Components" buttons work properly
- When a new component is added to a step, the component is immediately expanded
- When a new step is created, all the components in the step are immediately expanded

Closes #1199

### CODE REVIEW

**Review by hirokiterashima — CHANGES_REQUESTED** [review]
Looking good. I found some minor issues:

1. When I create a new step with "Automated Assessment" or "Interactive Simulation", the component(s) are not expanded.
2. Can you make the Expand All/Collapse All buttons grayed out if all the components are expanded/collapsed?
3. The border around the boxes with the right angles makes the page feel a bit harsh. What if we use rounded corners and/or softer lines, colors, gradients? @breity can you see if you can make it feel a bit less angular and more friendly?

**Comment by hirokiterashima** [comment]
New fixes look good. 👍 I'll review again after style changes are made.

**Review by breity — APPROVED** [review]
Works well.

I updated styles a bit. Gave components a border-radius and lightened the color. I changed the expand/collapse all icons to regular text buttons that better match similar buttons in the Teacher Tools. I also added some aria-label attributes.

After we convert node authoring to Angular, we can work on styles/UI some more.

**Review by hirokiterashima — APPROVED** [review]
New styles look great.

**Pull request merged**
