### PR TITLE
refactor(Authoring): Rename nodeIdToInsertInsideOrAfter to targetLocation

### LINKED ISSUE #1738: refactor(Authoring): Rename nodeIdToInsertInsideOrAfter to targetLocation
In the add step components, rename the variable nodeIdToInsertInsideOrAfter to targetLocation.

### PR DESCRIPTION
**Pull request by geoffreykwan**
## Changes
- Renamed the variable nodeIdToInsertInsideOrAfter to targetLocation

## Test
- Make sure all the add step routes still work properly

Closes #1738

### CODE REVIEW

**Comment by hirokiterashima** [comment]
I think ```targetLocation``` is a bit vague. Since we know that they'll all be ID's, should the name be ```targetId``` to be more specific? We use ```targetId``` in other places too atm.

**Comment by geoffreykwan** [comment]
Ok, I've changed the variable name to `targetId`.

**Review by hirokiterashima — APPROVED** [review]
LGTM

**Pull request merged**
