### PR TITLE
feat(MathJax): Render math equations in unit content

### LINKED ISSUE #812: Add MathJax integration
### Description

Use [MathJax](https://www.mathjax.org/) to allow authors to display math equations in unit content, like prompts, mc items, match items, etc.

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Add MathJax library to render math equations in unit content (html, prompt, MC item, etc)

## Test Prep
- Run ```npm install``` to get the new library

## Test
1. Add this to html or prompts and see that the equation renders nicely
```
When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
```
2. Add MathML to OR prompt and see that the equation renders nicely
```
<p>
When
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>a</mi><mo>&#x2260;</mo><mn>0</mn>
</math>,
there are two solutions to
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>a</mi><msup><mi>x</mi><mn>2</mn></msup>
  <mo>+</mo> <mi>b</mi><mi>x</mi>
  <mo>+</mo> <mi>c</mi> <mo>=</mo> <mn>0</mn>
</math>
and they are
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>x</mi> <mo>=</mo>
  <mrow>
    <mfrac>
      <mrow>
        <mo>&#x2212;</mo>
        <mi>b</mi>
        <mo>&#x00B1;</mo>
        <msqrt>
          <msup><mi>b</mi><mn>2</mn></msup>
          <mo>&#x2212;</mo>
          <mn>4</mn><mi>a</mi><mi>c</mi>
        </msqrt>
      </mrow>
      <mrow>
        <mn>2</mn><mi>a</mi>
      </mrow>
    </mfrac>
  </mrow>
  <mtext>.</mtext>
</math>
</p>
```
4. Add this to MC item text, match choice text, etc and see that they render nicely
```$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$```
5. Try other equations 

Closes #812

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
MathJax works well in the VLE but does not render right away in the Classroom Monitor. In this example I have Multiple Choice choices that contain MathJax and the student chose the first choice.

Screenshot 2022-09-15 151456

If you click the "Step Info" button, the MathJax will then be rendered properly. Rendering the step in the "Step Info" popup seems to trigger the rendering of the MathJax everywhere.

Screenshot 2022-09-15 151523

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
- Student Discussion post with Math Jax code does not render immediately after posting. If you leave the step and come back, it will be rendered properly.
- Peer Chat post with Math Jax code never renders in student or grading views.
- Table with Math Jax code in student view does not render. I think this used to work.
- Table with Math Jax code in grading view initially does not render but if you click "Step Info" it will then render.

**Comment by hirokiterashima** [comment]
Good catch. Fixed the issue in table with Math Jax code in grading view initially does not render but if you click "Step Info" it will then render.

Since this PR is about adding MathJax library to render math equations in unit content (html, prompt, MC item, etc), let's focus on that instead and work on rendering MathJax in student response in a different PR.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
