### PR TITLE
feat(a11y): Add keyboard accessibility to AT node authoring

### LINKED ISSUE #1948: feat(a11y): Add keyboard accessibility to AT node authoring
## Description
Some action elements in the Authoring Tool step (node) authoring components are not keyboard accessible. All elements should be navigable and selectable using the keyboard.

### PR DESCRIPTION
**Pull request by breity**
## Changes
- Make all action elements/buttons on components in Authoring Tool step (node) authoring are keyboard accessible.
- Use MatExpansionPanel for components.
- Move add new component buttons next to components to match lesson and step authoring.

## Test
- Make sure expand all and collapse all buttons in AT node authoring work as before.
- Make sure components can still be expanded/collapsed by clicking on lesson.
- Make sure all action icons on components still work as before.
- Make sure you can use the keyboard to navigate to components and all their action icons and the icon buttons work using the keyboard (enter key or space bar for checkboxes).

Closes #1948.

### CODE REVIEW

**Review by hirokiterashima — COMMENTED** [review]
Looks like I can't select the component checkbox with the spacebar?

Everything else looks good.

**Comment by breity** [comment]
@hirokiterashima Ah, yep. Thanks for catching that. Should be fixed now.

**Review by hirokiterashima — APPROVED** [review]
LGTM

**Comment by hirokiterashima** [comment]
I just noticed an extra padding to the right of the wrench icon in step authoring. I don't see this in production, so I wonder if it was introduced in this PR? If it's easy, can you fix it before merge?
Screenshot 2024-09-20 at 8 11 14 AM

**Pull request merged**
