### PR TITLE
refactor(Project Authoring): Clean up template

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes (mostly in project-authoring.component.html)
- Aria-label now says "Select step/lesson" instead of node title
- Remove the 'group0' master root node from consideration in code instead of template
- Remove unnecessary divs and styles

## Test
- Project editing page looks and works as before, specifically:
   - Shows node icon and title as before for active and inactive lessons/steps
   - Shows pointer for mouse when hovering over node item
   - Scrolls to and highlights newly added step

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Mostly works except now you have to click on the step title text in order to go into the step. Previously you could click anywhere on the colored bar to go into the step.

**Comment by hirokiterashima** [comment]
Good catch. PTAL.

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Now when you click on the icon or the step title, it checks the checkbox. Before if you clicked on the icon or step title it would open the step.

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Clicking now works like it used to but the steps in "Unused Lessons" and "Unused Steps" now have a newline after the checkbox.

Screenshot 2023-10-20 115353

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
