### PR TITLE
chore(Authoring Tool): Convert to Angular

### LINKED ISSUE #1381: chore(Authoring Tool): Convert to Angular

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Upgrade AuthoringToolComponent to Angular

## Test
- AT works as before, esp. using sidenav and side menu

Closes #1381

### CODE REVIEW

**Review by breity — CHANGES_REQUESTED** [review]
Looks good for the most part. I fixed the page scrolling problem and other layout/style issues.

One remaining issue I see is that the project list link in the authoring menu doesn't work anymore. Selecting it results in a blank page.

**Comment by hirokiterashima** [comment]
Can you clarify what you mean by "project list link in the authoring menu"? Do you mean the "Unit List" icon button on the side panel (see below)? Clicking on the icon (in the side nav and also the one in the slide-out menu) properly takes me to the unit list page for me. Do you see any errors in the console? Is it unit-specific?
Screenshot 2023-08-08 at 8 48 16 AM

**Comment by breity** [comment]
Yep, it was that button that I was talking about.

I recompiled wise-client and the problem was fixed. I'll go ahead and approve. Thanks.

**Review by breity — APPROVED** [review]

**Pull request merged**
